public enum BudgetCategory
{
    Venue,
    Catering,
    Photography,
    Videography,
    Invitations,
    Transportation,
    Rentals,
    Attire,
    HairAndMakeup,
    Favors,
    WeddingPlanner,
    Officiant,
    Gifts,
    Miscellaneous,
    Florist,
    Entertainment,
    DressDesigner,
    CakeBaker,
    Decorator,
    MusicBand,
    JewelryDesigner
}